### ISSUE TITLE
About PPO on discrete LunarLander

### ISSUE THREAD

**Issue by weak-orange-wind** [RLOpensource/tensorflow_RL#53]
I have tried single process PPO on LunarLander-v2 and the learned agent is always flying on the sky, did you have similar problem?

**Comment by tinker495** [comment]
How About on A2C? it's flying on the sky too? It could help us figure out what's wrong with that.

**Comment by weak-orange-wind** [comment]
I solved this problem by using multi workers,.Thank you!
